In [1]:
pip install pandas tabula-py PyPDF2

Requirement already satisfied: pandas in c:\users\sambit\anaconda3\lib\site-packages (1.5.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: tabula-py in c:\users\sambit\anaconda3\lib\site-packages (2.9.0)
Requirement already satisfied: PyPDF2 in c:\users\sambit\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sambit\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sambit\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sambit\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: distro in c:\users\sambit\anaconda3\lib\site-packages (from tabula-py) (1.9.0)
Requirement already satisfied: six>=1.5 in c:\users\sambit\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [6]:
pip install tabula-py

Requirement already satisfied: tabula-py in c:\users\sambit\anaconda3\lib\site-packages (2.9.0)
Requirement already satisfied: pandas>=0.25.3 in c:\users\sambit\anaconda3\lib\site-packages (from tabula-py) (1.5.3)
Requirement already satisfied: numpy in c:\users\sambit\anaconda3\lib\site-packages (from tabula-py) (1.24.3)
Requirement already satisfied: distro in c:\users\sambit\anaconda3\lib\site-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sambit\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sambit\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\sambit\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install PyPDF2

Requirement already satisfied: PyPDF2 in c:\users\sambit\anaconda3\lib\site-packages (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
tabula-py PyPDF2

In [1]:
import tabula
import pandas as pd

In [3]:
# Path to your PDF file

In [2]:
pdf_path = "D:\Directory of Institution - University 05022024070841190PM.pdf"


dfs = tabula.read_pdf(pdf_path, pages='all', multiple_tables=True)
df=pd.concat(dfs)

In [ ]:
df.shape

In [18]:
data_frame

NameError: name 'data_frame' is not defined

In [3]:
df

,State,District,University Type,University Name,Address,Website,Year When\rDecalred\rUniversity,Specialised in,Location,Upload Year,...,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Year When,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA\rENGINEERING\rSCIENCE AND\rTECHNOLOGY...,"BEST Innovation\rUniversity,\rGownivaripalli,\...",bestiu.edu.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,Anantapur,Central University,CENTRAL\rUNIVERSITY OF\rANDHRA PRADESH\r(Id: U...,"Central University\rof Andhra\rPradesh, JNTU\r...",https://cuap.ac.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru\rTechnological\rUniversity, A...","Sir\rMokshagundam\rVisheswaraiah\rRoad, JNTUA\...",www.jntua.ac.in,2008.0,Technical,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya\rUniversity, Anantapur\r(I...","Sri Venakteswara\rPuram, Sri\rVenkateswara\rPu...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,West Bengal,Paschim Bardhaman,State Public University,"KAZI NAZRUL\rUNIVERSITY,\rASANSOL (Id: U-0718)","Nazrul Road,\rKalla Bypass\rMore, P.O. - Kalla...",http://www.knu.ac.\rin,2012.0,No,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,West Bengal,Purba Bardhaman,Institute of National\rImportance,"National Institute of\rTechnology, Durgapur\r(...","National Institute\rof Technology\rDurgapur,\r...",www.nitdgp.ac.in,2004.0,No,Urban,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,West Bengal,Purba Bardhaman,State Public University,The University of\rBurdwan (Id: U-0569),"Rajbati, Burdwan",www.buruniv.ac.in,1960.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,West Bengal,Purulia,State Public University,Sidho-Kanho Birsa\rUniversity (Id: U-0583),"Ranchi Road, PO\r- Sainik School,\rPurulia, PI...",www.skbu.ac.in,2010.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1=df.copy()

In [5]:
df1

,State,District,University Type,University Name,Address,Website,Year When\rDecalred\rUniversity,Specialised in,Location,Upload Year,...,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Year When,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA\rENGINEERING\rSCIENCE AND\rTECHNOLOGY...,"BEST Innovation\rUniversity,\rGownivaripalli,\...",bestiu.edu.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,Anantapur,Central University,CENTRAL\rUNIVERSITY OF\rANDHRA PRADESH\r(Id: U...,"Central University\rof Andhra\rPradesh, JNTU\r...",https://cuap.ac.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru\rTechnological\rUniversity, A...","Sir\rMokshagundam\rVisheswaraiah\rRoad, JNTUA\...",www.jntua.ac.in,2008.0,Technical,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya\rUniversity, Anantapur\r(I...","Sri Venakteswara\rPuram, Sri\rVenkateswara\rPu...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,West Bengal,Paschim Bardhaman,State Public University,"KAZI NAZRUL\rUNIVERSITY,\rASANSOL (Id: U-0718)","Nazrul Road,\rKalla Bypass\rMore, P.O. - Kalla...",http://www.knu.ac.\rin,2012.0,No,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,West Bengal,Purba Bardhaman,Institute of National\rImportance,"National Institute of\rTechnology, Durgapur\r(...","National Institute\rof Technology\rDurgapur,\r...",www.nitdgp.ac.in,2004.0,No,Urban,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,West Bengal,Purba Bardhaman,State Public University,The University of\rBurdwan (Id: U-0569),"Rajbati, Burdwan",www.buruniv.ac.in,1960.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,West Bengal,Purulia,State Public University,Sidho-Kanho Birsa\rUniversity (Id: U-0583),"Ranchi Road, PO\r- Sainik School,\rPurulia, PI...",www.skbu.ac.in,2010.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962 entries, 0 to 2
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               565 non-null    object
 1   District                            565 non-null    object
 2   University Type                     565 non-null    object
 3   University Name                     565 non-null    object
 4   Address                             526 non-null    object
 5   Website                             523 non-null    object
University       526 non-null    float64
 7   Specialised in                      526 non-null    object
 8   Location                            526 non-null    object
 9   Upload Year                         565 non-null    object
Survey Year  565 non-null    float64
 11  Unnamed: 0                          784 non-null    object
 12  Unnamed: 1                          332 non-null    object
 13  Unnamed: 2                          600 non-null    object
 14  Unnamed: 3                          793 non-null    object
 15  Unnamed: 4                          2180 non-null   object
 16  Unnamed: 5                          3102 non-null   object
 17  Unnamed: 6                          1676 non-null   object
 18  Year When                           899 non-null    object
 19  Unnamed: 7                          932 non-null    object
 20  Unnamed: 8                          838 non-null    object
 21  Unnamed: 9                          868 non-null    object
 22  Unnamed: 10                         922 non-null    object
 23  Unnamed: 11                         233 non-null    object
dtypes: float64(2), object(22)
memory usage: 1.1+ MB

In [9]:
df1.head(20)

,State,District,University Type,University Name,Address,Website,Year When\rDecalred\rUniversity,Specialised in,Location,Upload Year,...,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Year When,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA\rENGINEERING\rSCIENCE AND\rTECHNOLOGY...,"BEST Innovation\rUniversity,\rGownivaripalli,\...",bestiu.edu.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,Anantapur,Central University,CENTRAL\rUNIVERSITY OF\rANDHRA PRADESH\r(Id: U...,"Central University\rof Andhra\rPradesh, JNTU\r...",https://cuap.ac.in,2018.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru\rTechnological\rUniversity, A...","Sir\rMokshagundam\rVisheswaraiah\rRoad, JNTUA\...",www.jntua.ac.in,2008.0,Technical,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya\rUniversity, Anantapur\r(I...","Sri Venakteswara\rPuram, Sri\rVenkateswara\rPu...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Andhra Pradesh,Chittoor,State Public University,"Dravidian University,\rKuppam, Chittoor\rDistr...","DRAVIDIAN\rUNIVERSITY,\rSRINIVASAVANA\rM, KUPP...",www.dravidianuni\rversity.ac.in,1997.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andhra Pradesh,Chittoor,Institute of National\rImportance,"INDIAN INSTITUTE OF\rINFORMATION\rTECHNOLOGY,\...","630, Gnan Marg,\rSri City, Tirupati\rDistrict,...",www.iiits.ac.in,2017.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Andhra Pradesh,Chittoor,Institute of National\rImportance,Indian Institute of\rScience Education &\rRese...,Indian Institute of\rScience\rEducation and\rR...,www.iisertirupati.a\rc.in,2015.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Andhra Pradesh,Chittoor,Institute of National\rImportance,"Indian Institute of\rTechnology, Tirupati\r(Id...","Yerpedu -\rVenkatagiri Road,\rYerpedu Post,\rT...",http://iittp.ac.in,2016.0,No,Rural,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Andhra Pradesh,Chittoor,State Private University,KREA UNIVERSITY (Id:\rU-1111),"5655 Central\rExpressway,\rSricity,",krea.edu.in,2018.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Andhra Pradesh,Chittoor,Central University,"National Sanskrit\rUniversity , Tirupati (Id:\...","Central University,\rNear Balaji\rColony, Tiru...",nsktu.ac.in,2020.0,No,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1,2,3,4,5,6,7.0,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Chittoor,State Public University,"Sri Padmavathi Mahila\rVisva Vidyalayam,\rTiru...","Tirupati , Sri\rPadmavati Mahila\rVisvavidyala...",www.spmvv.ac.in,1983.0,No,Urban,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,Chittoor,Institute under State\rLegislature Act,Sri Venkateswara\rInstitute of Medical\rScienc...,"Alipiri Road,\rDirector-cum-Vice\rChancellor,\...",https://svimstpt.ap\r.nic.in,1995.0,No,Urban,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,Chittoor,State Public University,"Sri Venkateswara\rUniversity, Tirupathy\r(Id: ...","Sri Venkateswara\rUniversity,\rTirupati, NULL,...",www.svuniversity.\redu.in,1954.0,No,Urban,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Chittoor,State Public University,"Sri Venkateswara Vedic\rUniversity, Tirpupathi...","Alipiri-Chandragiri\rBypass Road,\rTirupati",www.svvedicunive\rrsity.ac.in,2006.0,Veda,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Andhra Pradesh,Chittoor,State Public University,"Sri Venkateswara\rVeterinary University,\rTiru...","Admn.Office: Dr\rYSR Bhavan,\rTirupati, Tirupati",www.svvu.edu.in,2005.0,No,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andhra Pradesh,East Godavari,State Public University,"Adikavi Nannaya\rUniversity,\rRajahmundry, Eas...","Raja Raja\rNarendra Nagar,\rRajanagaram\r(Mand...",www.aknu.edu.in,2006.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Andhra Pradesh,East Godavari,State Public University,"Jawaharlal Nehru\rTechnological\rUniversity, K...","Pitapuram Road,\rKAKINADA",www.jntuk.edu.in,2008.0,No,Urban,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Andhra Pradesh,Guntur,State Public University,"Acharya Nagarjuna\rUniversity, Guntur (Id:\rU-...","Dean,, Acharya\rNagarjuna\rUniversity, Guntur",www.anu.ac.in,1980.0,No,Rural,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
c=df1.drop(["Unnamed: 3","Unnamed: 4","Unnamed: 1","Unnamed: 2","Unnamed: 5","Unnamed: 6","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 0","Unnamed: 11","Year When"],axis=1)

In [11]:
final_df=c.drop(0)

In [27]:
final_df

,State,District,University Type,University Name,Address,Website,Year When\rDecalred\rUniversity,Specialised in,Location,Upload Year,The Institute Added In\rSurvey Year
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA\rENGINEERING\rSCIENCE AND\rTECHNOLOGY...,"BEST Innovation\rUniversity,\rGownivaripalli,\...",bestiu.edu.in,2018.0,No,Rural,2021,2020.0
2,Andhra Pradesh,Anantapur,Central University,CENTRAL\rUNIVERSITY OF\rANDHRA PRADESH\r(Id: U...,"Central University\rof Andhra\rPradesh, JNTU\r...",https://cuap.ac.in,2018.0,No,Rural,2021,2018.0
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru\rTechnological\rUniversity, A...","Sir\rMokshagundam\rVisheswaraiah\rRoad, JNTUA\...",www.jntua.ac.in,2008.0,Technical,Rural,2021,2010.0
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya\rUniversity, Anantapur\r(I...","Sri Venakteswara\rPuram, Sri\rVenkateswara\rPu...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,2010.0
5,Andhra Pradesh,Chittoor,State Public University,"Dravidian University,\rKuppam, Chittoor\rDistr...","DRAVIDIAN\rUNIVERSITY,\rSRINIVASAVANA\rM, KUPP...",www.dravidianuni\rversity.ac.in,1997.0,No,Rural,2022,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
9,West Bengal,Nadia,State Public University,Maulana Abul Kalam\rAzad University of\rTechno...,"NH-12,\rHaringhata, PO-\rSimhat,\rHaringhata",http://makautwb.a\rc.in,2000.0,No,Rural,2022,2010.0
10,West Bengal,Paschim Bardhaman,State Public University,"KAZI NAZRUL\rUNIVERSITY,\rASANSOL (Id: U-0718)","Nazrul Road,\rKalla Bypass\rMore, P.O. - Kalla...",http://www.knu.ac.\rin,2012.0,No,Urban,2021,2013.0
11,West Bengal,Purba Bardhaman,Institute of National\rImportance,"National Institute of\rTechnology, Durgapur\r(...","National Institute\rof Technology\rDurgapur,\r...",www.nitdgp.ac.in,2004.0,No,Urban,2022,2010.0
1,West Bengal,Purba Bardhaman,State Public University,The University of\rBurdwan (Id: U-0569),"Rajbati, Burdwan",www.buruniv.ac.in,1960.0,No,Rural,2021,2010.0
2,West Bengal,Purulia,State Public University,Sidho-Kanho Birsa\rUniversity (Id: U-0583),"Ranchi Road, PO\r- Sainik School,\rPurulia, PI...",www.skbu.ac.in,2010.0,No,Rural,2022,2010.0

In [12]:
final_df.shape

(5849, 11)

In [ ]:
#correcting the format of the strings by omitting the "\r" present in them

In [13]:
exp_df=final_df.copy()

In [14]:
exp_df['University Name']=exp_df['University Name'].str.replace(r'\r',' ')

C:\Users\Sambit\AppData\Local\Temp\ipykernel_57584\2028143373.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  exp_df['University Name']=exp_df['University Name'].str.replace(r'\r',' ')

In [15]:
exp_df['Address']=exp_df['Address'].str.replace(r'\r',' ')

C:\Users\Sambit\AppData\Local\Temp\ipykernel_57584\799336338.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  exp_df['Address']=exp_df['Address'].str.replace(r'\r',' ')

In [35]:
exp_df

,State,District,University Type,University Name,Address,Website,Year When Decalred University,Specialised in,Location,Upload Year,The Institute Added In Survey Year
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA ENGINEERING SCIENCE AND TECHNOLOGY IN...,"BEST Innovation University, Gownivaripalli, Go...",bestiu.edu.in,2018.0,No,Rural,2021,2020.0
2,Andhra Pradesh,Anantapur,Central University,CENTRAL UNIVERSITY OF ANDHRA PRADESH (Id: U-0976),"Central University of Andhra Pradesh, JNTU Inc...",https://cuap.ac.in,2018.0,No,Rural,2021,2018.0
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru Technological University, Ana...","Sir Mokshagundam Visheswaraiah Road, JNTUA Col...",www.jntua.ac.in,2008.0,Technical,Rural,2021,2010.0
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya University, Anantapur (Id:...","Sri Venakteswara Puram, Sri Venkateswara Puram...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,2010.0
5,Andhra Pradesh,Chittoor,State Public University,"Dravidian University, Kuppam, Chittoor Distric...","DRAVIDIAN UNIVERSITY, SRINIVASAVANA M, KUPPAM,...",www.dravidianuni\rversity.ac.in,1997.0,No,Rural,2022,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
9,West Bengal,Nadia,State Public University,Maulana Abul Kalam Azad University of Technolo...,"NH-12, Haringhata, PO- Simhat, Haringhata",http://makautwb.a\rc.in,2000.0,No,Rural,2022,2010.0
10,West Bengal,Paschim Bardhaman,State Public University,"KAZI NAZRUL UNIVERSITY, ASANSOL (Id: U-0718)","Nazrul Road, Kalla Bypass More, P.O. - Kalla C...",http://www.knu.ac.\rin,2012.0,No,Urban,2021,2013.0
11,West Bengal,Purba Bardhaman,Institute of National\rImportance,"National Institute of Technology, Durgapur (Id...","National Institute of Technology Durgapur, Mah...",www.nitdgp.ac.in,2004.0,No,Urban,2022,2010.0
1,West Bengal,Purba Bardhaman,State Public University,The University of Burdwan (Id: U-0569),"Rajbati, Burdwan",www.buruniv.ac.in,1960.0,No,Rural,2021,2010.0
2,West Bengal,Purulia,State Public University,Sidho-Kanho Birsa University (Id: U-0583),"Ranchi Road, PO - Sainik School, Purulia, PIN ...",www.skbu.ac.in,2010.0,No,Rural,2022,2010.0

In [33]:
exp_df.isnull().count()

State                                  5849
District                               5849
University Type                        5849
University Name                        5849
Address                                5849
Website                                5849
Year When\rDecalred\rUniversity        5849
Specialised in                         5849
Location                               5849
Upload Year                            5849
The Institute Added In\rSurvey Year    5849
dtype: int64

In [86]:
#while loading the pdf file by concanteting due to some unseen error rows were multiplied with null values,so we drop all those row

SyntaxError: invalid syntax (791002224.py, line 2)

In [18]:
exp_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5849 entries, 1 to 2
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               518 non-null    object
 1   District                            518 non-null    object
 2   University Type                     518 non-null    object
 3   University Name                     518 non-null    object
 4   Address                             479 non-null    object
 5   Website                             476 non-null    object
University       479 non-null    float64
 7   Specialised in                      479 non-null    object
 8   Location                            479 non-null    object
 9   Upload Year                         518 non-null    object
Survey Year  518 non-null    float64
dtypes: float64(2), object(9)
memory usage: 548.3+ KB

In [34]:
exp_df

,State,District,University Type,University Name,Address,Website,Year When Decalred University,Specialised in,Location,Upload Year,The Institute Added In Survey Year
1,Andhra Pradesh,Anantapur,State Private University,BHARTIYA ENGINEERING SCIENCE AND TECHNOLOGY IN...,"BEST Innovation University, Gownivaripalli, Go...",bestiu.edu.in,2018.0,No,Rural,2021,2020.0
2,Andhra Pradesh,Anantapur,Central University,CENTRAL UNIVERSITY OF ANDHRA PRADESH (Id: U-0976),"Central University of Andhra Pradesh, JNTU Inc...",https://cuap.ac.in,2018.0,No,Rural,2021,2018.0
3,Andhra Pradesh,Anantapur,State Public University,"Jawaharlal Nehru Technological University, Ana...","Sir Mokshagundam Visheswaraiah Road, JNTUA Col...",www.jntua.ac.in,2008.0,Technical,Rural,2021,2010.0
4,Andhra Pradesh,Anantapur,State Public University,"Sri Krishnadevaraya University, Anantapur (Id:...","Sri Venakteswara Puram, Sri Venkateswara Puram...",www.skuniversity.\rac.in,1981.0,No,Rural,2021,2010.0
5,Andhra Pradesh,Chittoor,State Public University,"Dravidian University, Kuppam, Chittoor Distric...","DRAVIDIAN UNIVERSITY, SRINIVASAVANA M, KUPPAM,...",www.dravidianuni\rversity.ac.in,1997.0,No,Rural,2022,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
9,West Bengal,Nadia,State Public University,Maulana Abul Kalam Azad University of Technolo...,"NH-12, Haringhata, PO- Simhat, Haringhata",http://makautwb.a\rc.in,2000.0,No,Rural,2022,2010.0
10,West Bengal,Paschim Bardhaman,State Public University,"KAZI NAZRUL UNIVERSITY, ASANSOL (Id: U-0718)","Nazrul Road, Kalla Bypass More, P.O. - Kalla C...",http://www.knu.ac.\rin,2012.0,No,Urban,2021,2013.0
11,West Bengal,Purba Bardhaman,Institute of National\rImportance,"National Institute of Technology, Durgapur (Id...","National Institute of Technology Durgapur, Mah...",www.nitdgp.ac.in,2004.0,No,Urban,2022,2010.0
1,West Bengal,Purba Bardhaman,State Public University,The University of Burdwan (Id: U-0569),"Rajbati, Burdwan",www.buruniv.ac.in,1960.0,No,Rural,2021,2010.0
2,West Bengal,Purulia,State Public University,Sidho-Kanho Birsa University (Id: U-0583),"Ranchi Road, PO - Sainik School, Purulia, PIN ...",www.skbu.ac.in,2010.0,No,Rural,2022,2010.0

In [87]:
#finally our dataset is ready

In [32]:
exp_df.dropna(how='all',inplace=True)

In [33]:
exp_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518 entries, 1 to 2
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               518 non-null    object
 1   District                            518 non-null    object
 2   University Type                     518 non-null    object
 3   University Name                     518 non-null    object
 4   Address                             479 non-null    object
 5   Website                             476 non-null    object
 6   Year When Decalred University       479 non-null    float64
 7   Specialised in                      479 non-null    object
 8   Location                            479 non-null    object
 9   Upload Year                         518 non-null    object
 10  The Institute Added In Survey Year  518 non-null    float64
dtypes: float64(2), object(9)
memory usage: 48.6+ KB

In [49]:
#null values present in "year when declared University","address","location","specialised in","website"

In [28]:
exp_df.rename(columns={'Year When\rDecalred\rUniversity': 'Year When Decalred University'}, inplace=True)

In [29]:
exp_df.rename(columns={'The Institute Added In\rSurvey Year': 'The Institute Added In Survey Year'}, inplace=True)